_wandb:
    value:
        cli_version: 0.25.0
        e:
            idjdaoq0epvh92corrgquvg6yta1g88c:
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "940746641408"
                        used: "812137930752"
                email: allie11@stanford.edu
                executable: /home/allie11/miniconda3/envs/sim/bin/python
                git:
                    commit: d8be8b247d20f845939315006b6bc053e0ebe849
                    remote: https://github.com/alliegriffith/nonAdv.git
                gpu: NVIDIA H100 NVL
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-87eddc1a-2dbe-1bf5-a80b-4b0dbfe60ad0
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-6a8f7138-4010-077f-7054-017d9e659ef8
                host: longbeach
                memory:
                    total: "540510056448"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: -m examples.run_cem
                python: CPython 3.11.14
                root: /home/allie11/SimVBG
                startedAt: "2026-03-20T21:54:05.800923Z"
                writerId: idjdaoq0epvh92corrgquvg6yta1g88c
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "6": 5.3.0
            "12": 0.25.0
            "13": linux-x86_64
age_clip:
    value:
        - 10
        - 80
age_mean:
    value: 25
age_std:
    value: 10
beta_concentration:
    value: 10
beta_init_alpha:
    value: 1
beta_init_beta:
    value: 1
binarize_booleans:
    value: true
num_boolean_traits:
    value: 10
num_elites:
    value: 8
num_rollouts:
    value: 30
num_rounds:
    value: 20
num_turns:
    value: 3
output_file:
    value: cem_rollouts.json
p_clip:
    value:
        - 0.05
        - 0.95
